"""Tests for ReAct V2 wiring shared by the Wikipedia benchmarks."""

import random
import sys
from pathlib import Path

import pytest


sys.path.insert(0, str(Path(__file__).parents[1]))

from examples.common.experiment_models import (
    DEEPSEEK_V4_1_FLASH_MODEL,
    DEEPSEEK_V4_1_FLASH_REVISION,
    QWEN3_8_27B_MODEL,
    QWEN3_8_27B_REVISION,
    experiment_decoding,
    experiment_model_version,
    validate_experiment_model_pair,
)
from examples.common.react_v2 import (
    build_react_v2_strategy,
    resolve_template_family,
    structured_prompt,
)
from examples.hotpotqa.benchmark_settings import SEED_CANDIDATE
from gepa.strategies.document_template import TEMPLATE_FAMILIES

LOCAL_API_BASE = "http://127.0.0.1:8000/v1"


def test_student_model_selects_provider_specific_template() -> None:
    """Infer Alibaba prompt structure from the Qwen student identifier."""
    assert resolve_template_family("auto", QWEN3_8_27B_MODEL) == "alibaba"


def test_structured_benchmark_seeds_follow_selected_template() -> None:
    """Render structured benchmark seeds only into Alibaba's objective section."""
    template = TEMPLATE_FAMILIES["alibaba"]["system_prompt"]
    prompt = structured_prompt("Retrieve two evidence hops.", "alibaba")

    assert template.parse(prompt)["Objective"] == "Retrieve two evidence hops."
    assert [line for line in prompt.splitlines() if line.startswith("## ")] == ["## Objective"]
    assert all(
        template.parse(text)["Objective"]
        for text in {key: structured_prompt(value, "alibaba") for key, value in SEED_CANDIDATE.items()}.values()
    )
    for text in {key: structured_prompt(value, "alibaba") for key, value in SEED_CANDIDATE.items()}.values():
        bodies = template.parse(text)
        assert bodies["Objective"]
        assert all(not body for section, body in bodies.items() if section != "Objective")
        assert "not specified" not in text.lower()


def test_hotpot_seed_instructions_match_the_artifact_signatures() -> None:
    """Lock the four initial instructions generated by DSPy signatures."""
    assert SEED_CANDIDATE == {
        "summarize1": "Given the fields `question`, `passages`, produce the fields `summary`.",
        "create_query_hop2": "Given the fields `question`, `summary_1`, produce the fields `query`.",
        "summarize2": "Given the fields `question`, `context`, `passages`, produce the fields `summary`.",
        "final_answer": "Given the fields `question`, `summary_1`, `summary_2`, produce the fields `answer`.",
    }


@pytest.mark.parametrize(
    ("family", "component_kind", "task_section"),
    [
        ("generic", "system_prompt", "Task"),
        ("generic", "user_prompt", "Task"),
        ("openai", "system_prompt", "Instructions"),
        ("openai", "user_prompt", "Input"),
        ("anthropic", "system_prompt", "Instructions"),
        ("anthropic", "user_prompt", "Instructions"),
        ("google", "system_prompt", "Instructions"),
        ("google", "user_prompt", "Task"),
        ("alibaba", "system_prompt", "Objective"),
        ("alibaba", "user_prompt", "Objective"),
    ],
)
def test_structured_prompt_populates_only_the_role_specific_task_section(
    family: str,
    component_kind: str,
    task_section: str,
) -> None:
    """Keep seed content in the correct message-role schema without placeholders.

    Args:
        family: Provider template family under test.
        component_kind: System or user message role.
        task_section: Section expected to receive seed text.
    """
    template = TEMPLATE_FAMILIES[family][component_kind]
    prompt = structured_prompt("Do the task.", family, component_kind)
    bodies = template.parse(prompt)
    assert bodies[task_section] == "Do the task."
    assert all(not body for section, body in bodies.items() if section != task_section)


@pytest.mark.parametrize(
    ("model", "expected_family"),
    [(QWEN3_8_27B_MODEL, "alibaba"), (DEEPSEEK_V4_1_FLASH_MODEL, "generic")],
)
def test_experiment_model_pairs_build_without_running_an_experiment(model: str, expected_family: str) -> None:
    """Build each homogeneous model condition without calling its model.

    Args:
        model: Exact model identifier assigned to both roles.
        expected_family: Provider template inferred for the student model.
    """
    strategy_rng = random.Random(7)
    strategy, family = build_react_v2_strategy(
        reflection_model=model,
        task_model=model,
        lm_kwargs={"api_base": "http://localhost:8000/v1"},
        level=2,
        edit_tool_set="broad",
        template_family="auto",
        component_kinds={"summarize1": "system_prompt"},
        rng=strategy_rng,
    )

    assert family == expected_family
    assert strategy.proposer_model == model
    assert strategy.component_kinds == {"summarize1": "system_prompt"}
    assert strategy.rng is strategy_rng
    assert strategy.max_chars is None
    assert {tool.value for tool in strategy.edit_tools} == {
        "INSERT_TEXT",
        "DELETE_TEXT",
        "REPLACE_TEXT",
        "MOVE_TEXT",
    }


@pytest.mark.parametrize("model", [QWEN3_8_27B_MODEL, DEEPSEEK_V4_1_FLASH_MODEL])
def test_role_specific_sampling_keeps_distinct_journal_namespaces(tmp_path: Path, model: str) -> None:
    """Share identical Controller/editor clients and isolate different sampling profiles."""
    strategy, family = build_react_v2_strategy(
        reflection_model=model,
        task_model=model,
        lm_kwargs={
            **experiment_decoding(model, agentic=False),
            "response_journal_path": str(tmp_path / "responses.sqlite3"),
        },
        level=2,
        edit_tool_set="broad",
        template_family="auto",
        react_top_p=float(experiment_decoding(model, agentic=True)["top_p"]),
        manifestor_temperature=1.0,
    )
    assert strategy.controller_lm is strategy.base_lm
    expected_namespaces = ("controller-proposer", "controller-proposer", "manifestor")
    assert (
        tuple(
            client._response_journal.namespace
            for client in (strategy.base_lm, strategy.controller_lm, strategy.manifestor_lm)
        )
        == expected_namespaces
    )
    contract = strategy.run_contract({"sys": structured_prompt("Answer accurately.", family, "system_prompt")})
    assert contract["controller_lm"]["completion_kwargs"]["top_p"] == experiment_decoding(model, agentic=False)["top_p"]
    assert contract["proposer_lm"]["completion_kwargs"]["top_p"] == 0.95


@pytest.mark.parametrize(
    ("model", "expected_version"),
    [
        (QWEN3_8_27B_MODEL, QWEN3_8_27B_REVISION),
        (DEEPSEEK_V4_1_FLASH_MODEL, DEEPSEEK_V4_1_FLASH_REVISION),
    ],
)
def test_experiment_models_resolve_to_declared_runtime_identities(model: str, expected_version: str) -> None:
    """Map each transport to its checkpoint, version, or rolling alias.

    Args:
        model: Canonical local model identifier.
        expected_version: Checkpoint revision, dated version, or direct alias.
    """
    actual_version = experiment_model_version(model)
    assert actual_version == expected_version


def test_experiment_model_version_rejects_unknown_models() -> None:
    """Refuse to give unapproved model names a scientific version identity."""
    unknown_model = "provider/unknown"
    with pytest.raises(ValueError, match="Unsupported experiment model"):
        experiment_model_version(unknown_model)


def test_experiment_model_pair_rejects_cross_model_runs() -> None:
    """Reject a Qwen student paired with the DeepSeek proposer."""
    with pytest.raises(ValueError, match="same model"):
        validate_experiment_model_pair(QWEN3_8_27B_MODEL, DEEPSEEK_V4_1_FLASH_MODEL)


def test_experiment_model_pair_rejects_unknown_models() -> None:
    """Reject homogeneous pairs outside the two configured experiment arms."""
    with pytest.raises(ValueError, match="Unsupported experiment model"):
        validate_experiment_model_pair("provider/unknown", "provider/unknown")
