"""Tests for ReAct V2 wiring shared by the Wikipedia benchmarks."""

import json
import random
import sys
from copy import deepcopy
from pathlib import Path
from types import SimpleNamespace

import litellm
import pytest

sys.path.insert(0, str(Path(__file__).parents[1]))

from examples.common.experiment_models import (
    DEEPSEEK_V4_FLASH_0731_OPENROUTER_MODEL,
    DEEPSEEK_V4_FLASH_MODEL,
    EXPERIMENT_NUM_RETRIES,
    QWEN3_8_27B_MODEL,
    QWEN3_8_27B_OPENROUTER_MODEL,
    experiment_decoding,
    experiment_request_overrides,
    resolve_experiment_model,
    validate_experiment_model_pair,
)
from examples.common.react_v2 import (
    build_react_v2_strategy,
    ensure_wikipedia_run_contract,
    resolve_template_family,
    structured_prompt,
)
from examples.hotpotqa.main import _run_key as hotpotqa_run_key
from examples.hotpotqa.main import build_config as build_hotpotqa_config
from examples.hotpotqa.main import build_run_contract as build_hotpotqa_run_contract
from examples.hotpotqa.main import dump_candidates as dump_hotpotqa_candidates
from examples.hotpotqa.main import seed_candidate as hotpotqa_seed_candidate
from examples.hover.main import _run_key as hover_run_key
from examples.hover.main import build_config as build_hover_config
from examples.hover.main import build_run_contract as build_hover_run_contract
from examples.hover.main import dump_candidates as dump_hover_candidates
from examples.hover.main import seed_candidate as hover_seed_candidate
from gepa.strategies.action_space import stateless_selector_policy_contract
from gepa.strategies.document_template import TEMPLATE_FAMILIES
from gepa.strategies.instruction_proposal import InstructionProposalSignature
from gepa.strategies.intervention import (
    CONTROLLER_POLICY_CONTRACT,
    SEMANTIC_ACTION_CATALOGS,
    SEMANTIC_ACTIONS,
    STATELESS_ACTION_MENU_VERSION,
    StatelessActionConstraint,
)


def test_student_model_selects_provider_specific_template() -> None:
    """Infer Alibaba prompt structure from the Qwen student identifier."""
    assert resolve_template_family("auto", QWEN3_8_27B_MODEL) == "alibaba"


def test_structured_benchmark_seeds_follow_selected_template() -> None:
    """Render structured benchmark seeds only into Alibaba's objective section."""
    template = TEMPLATE_FAMILIES["alibaba"]["system_prompt"]
    prompt = structured_prompt("Retrieve two evidence hops.", "alibaba")

    assert template.parse(prompt)["Objective"] == "Retrieve two evidence hops."
    assert [line for line in prompt.splitlines() if line.startswith("## ")] == ["## Objective"]
    assert all(
        template.parse(text)["Objective"]
        for text in hotpotqa_seed_candidate("2stage", "structured", "alibaba").values()
    )
    assert all(
        template.parse(text)["Objective"] for text in hover_seed_candidate("2stage", "structured", "alibaba").values()
    )
    for text in hotpotqa_seed_candidate("2stage", "structured", "alibaba").values():
        bodies = template.parse(text)
        assert bodies["Objective"]
        assert all(not body for section, body in bodies.items() if section != "Objective")
        assert "not specified" not in text.lower()


def test_hotpot_seed_instructions_match_the_artifact_signatures() -> None:
    """Lock the four initial instructions generated by DSPy signatures."""
    assert hotpotqa_seed_candidate("2stage", "plain", "generic") == {
        "summarize1": "Given the fields `question`, `passages`, produce the fields `summary`.",
        "create_query_hop2": "Given the fields `question`, `summary_1`, produce the fields `query`.",
        "summarize2": "Given the fields `question`, `context`, `passages`, produce the fields `summary`.",
        "final_answer": "Given the fields `question`, `summary_1`, `summary_2`, produce the fields `answer`.",
    }


def test_hover_seed_instructions_match_the_artifact_signatures() -> None:
    """Lock the four initial HoVer instructions generated by DSPy signatures."""
    assert hover_seed_candidate("2stage", "plain", "generic") == {
        "summarize1": "Given the fields `claim`, `passages`, produce the fields `summary`.",
        "create_query_hop2": "Given the fields `claim`, `summary_1`, produce the fields `query`.",
        "summarize2": "Given the fields `claim`, `context`, `passages`, produce the fields `summary`.",
        "create_query_hop3": "Given the fields `claim`, `summary_1`, `summary_2`, produce the fields `query`.",
    }


@pytest.mark.parametrize(
    ("family", "component_kind", "task_section"),
    [
        ("generic", "system_prompt", "Task"),
        ("generic", "user_prompt", "Task"),
        ("openai", "system_prompt", "Instructions"),
        ("openai", "user_prompt", "Input"),
        ("anthropic", "system_prompt", "Instructions"),
        ("anthropic", "user_prompt", "Instructions"),
        ("google", "system_prompt", "Instructions"),
        ("google", "user_prompt", "Task"),
        ("alibaba", "system_prompt", "Objective"),
        ("alibaba", "user_prompt", "Objective"),
    ],
)
def test_structured_prompt_populates_only_the_role_specific_task_section(
    family: str,
    component_kind: str,
    task_section: str,
) -> None:
    """Keep seed content in the correct message-role schema without placeholders.

    Args:
        family: Provider template family under test.
        component_kind: System or user message role.
        task_section: Section expected to receive seed text.
    """
    template = TEMPLATE_FAMILIES[family][component_kind]
    prompt = structured_prompt("Do the task.", family, component_kind)
    bodies = template.parse(prompt)
    assert bodies[task_section] == "Do the task."
    assert all(not body for section, body in bodies.items() if section != task_section)


@pytest.mark.parametrize(
    ("model", "expected_family"),
    [(QWEN3_8_27B_MODEL, "alibaba"), (DEEPSEEK_V4_FLASH_MODEL, "generic")],
)
def test_experiment_model_pairs_build_without_running_an_experiment(model: str, expected_family: str) -> None:
    """Build each homogeneous model condition without calling its model.

    Args:
        model: Exact model identifier assigned to both roles.
        expected_family: Provider template inferred for the student model.
    """
    strategy_rng = random.Random(7)
    strategy, family = build_react_v2_strategy(
        reflection_model=model,
        task_model=model,
        lm_kwargs={"api_base": "http://localhost:8000/v1"},
        level=2,
        edit_tool_set="broad",
        template_family="auto",
        component_kinds={"summarize1": "system_prompt"},
        rng=strategy_rng,
    )

    assert family == expected_family
    assert strategy.proposer_model == model
    assert strategy.component_kinds == {"summarize1": "system_prompt"}
    assert strategy.rng is strategy_rng
    assert {tool.value for tool in strategy.edit_tools} == {
        "INSERT_TEXT",
        "DELETE_TEXT",
        "REPLACE_TEXT",
        "MOVE_TEXT",
    }


def _hotpot_args(**overrides):
    """Build a complete HotPotQA argument namespace with targeted overrides.

    Args:
        **overrides: Values replacing the shared test defaults.

    Returns:
        Namespace accepted by both Wikipedia benchmark configuration builders.
    """
    values = {
        "api_profile": "direct",
        "api_base": None,
        "data_identity": {
            "source": {"type": "huggingface", "dataset": "hotpot_qa", "config": "fullwiki"},
            "splits": {"train": {"count": 150, "ids": ["train"], "sha256": "train-v1"}},
        },
        "data_path": None,
        "edit_tool_set": "broad",
        "max_workers": 32,
        "max_metric_calls": 100,
        "merge": False,
        "program": "2stage",
        "reflection_api_base": "http://localhost:8000/v1",
        "reflection_level": 2,
        "reflection_model": QWEN3_8_27B_MODEL,
        "retrieval_k": 7,
        "seed": 0,
        "seed_style": "structured",
        "solver_api_base": "http://localhost:8000/v1",
        "solver_model": QWEN3_8_27B_MODEL,
        "tag": "",
        "template_family": "auto",
        "test_limit": 300,
        "train_limit": 150,
        "val_limit": 300,
        "wiki17_dir": "/tmp/gepa-wiki17",
        "wikipedia_cache": "/tmp/gepa-wikipedia.sqlite3",
        "wikipedia_endpoint": "https://en.wikipedia.org/w/api.php",
        "wikipedia_timeout": 20.0,
    }
    values.update(overrides)
    return SimpleNamespace(**values)


def test_material_ablation_axes_get_distinct_resumable_run_keys() -> None:
    """Give edit-tool and reflection-level ablations distinct resume keys."""
    broad = hotpotqa_run_key("react_v2", _hotpot_args(edit_tool_set="broad"))
    minimal = hotpotqa_run_key("react_v2", _hotpot_args(edit_tool_set="minimal"))
    level_one = hotpotqa_run_key("react_v2", _hotpot_args(reflection_level=1))

    assert len({broad, minimal, level_one}) == 3
    assert "l2-broad" in broad


def test_complete_run_keys_cover_budget_seed_retrieval_and_data_identity() -> None:
    """Fingerprint every material model, budget, retrieval, and data axis."""
    base = hotpotqa_run_key("vanilla", _hotpot_args())
    changed = {
        hotpotqa_run_key("vanilla", _hotpot_args(max_metric_calls=101)),
        hotpotqa_run_key(
            "vanilla",
            _hotpot_args(solver_model=DEEPSEEK_V4_FLASH_MODEL, reflection_model=DEEPSEEK_V4_FLASH_MODEL),
        ),
        hotpotqa_run_key("vanilla", _hotpot_args(solver_api_base="https://solver.example/v1")),
        hotpotqa_run_key("vanilla", _hotpot_args(reflection_api_base="https://other-reflection.example/v1")),
        hotpotqa_run_key("vanilla", _hotpot_args(seed_style="plain")),
        hotpotqa_run_key("vanilla", _hotpot_args(retrieval_k=8)),
        hotpotqa_run_key(
            "vanilla",
            _hotpot_args(
                data_identity={
                    "source": {"type": "huggingface", "dataset": "hotpot_qa", "config": "fullwiki"},
                    "splits": {"train": {"count": 150, "ids": ["train"], "sha256": "train-v2"}},
                }
            ),
        ),
    }

    assert base not in changed
    assert len(changed) == 7
    vanilla_contract = build_hotpotqa_run_contract("vanilla", _hotpot_args())
    assert vanilla_contract["optimizer"]["reflection_level"] == 0
    assert vanilla_contract["optimizer"]["semantic_action_space"] is None
    assert vanilla_contract["optimizer"]["semantic_controller_policy"] is None
    level_one_contract = build_hotpotqa_run_contract("react_v2", _hotpot_args(reflection_level=1))
    assert level_one_contract["optimizer"]["semantic_action_space"] is None
    assert level_one_contract["optimizer"]["semantic_controller_policy"] is None


def test_hotpotqa_merge_is_an_opt_in_axis_shared_by_both_primary_conditions() -> None:
    """Keep the paper merge policy orthogonal to the reflection strategy."""
    no_merge_args = _hotpot_args()
    merge_args = _hotpot_args(merge=True)

    assert build_hotpotqa_run_contract("vanilla", no_merge_args)["optimizer"]["merge"] is None
    assert build_hotpotqa_config("vanilla", no_merge_args, {})[0].merge is None

    expected = {
        "max_merge_invocations": 5,
        "merge_val_overlap_floor": 5,
    }
    for condition in ("vanilla", "react_v2"):
        contract = build_hotpotqa_run_contract(condition, merge_args)
        config, _ = build_hotpotqa_config(condition, merge_args, {})

        assert contract["optimizer"]["merge"] == expected
        assert config.merge is not None
        assert config.merge.max_merge_invocations == 5
        assert config.merge.merge_val_overlap_floor == 5

    assert hotpotqa_run_key("vanilla", no_merge_args) != hotpotqa_run_key("vanilla", merge_args)
    assert hotpotqa_run_key("vanilla", merge_args).startswith("merge-")


def test_hotpot_and_hover_contracts_record_exact_model_pair() -> None:
    """Record the same experiment model and endpoint for both roles."""
    hotpot = build_hotpotqa_run_contract("react_v2", _hotpot_args())
    hover_args = _hotpot_args(final_retrieval_k=10)
    hover = build_hover_run_contract("react_v2", hover_args)

    for contract in (hotpot, hover):
        assert contract["models"]["solver"] == QWEN3_8_27B_MODEL
        assert contract["models"]["api_profile"] == "direct"
        assert contract["models"]["solver_runtime"] == QWEN3_8_27B_MODEL
        assert contract["models"]["solver_api_base"] == "http://localhost:8000/v1"
        assert contract["models"]["reflection"] == QWEN3_8_27B_MODEL
        assert contract["models"]["reflection_runtime"] == QWEN3_8_27B_MODEL
        assert contract["models"]["reflection_api_base"] == "http://localhost:8000/v1"
        assert contract["models"]["solver_decoding"] == experiment_decoding(QWEN3_8_27B_MODEL)
        assert contract["models"]["reflection_decoding"] == experiment_decoding(QWEN3_8_27B_MODEL)
        assert contract["models"]["solver_num_retries"] == EXPERIMENT_NUM_RETRIES
        assert contract["models"]["reflection_num_retries"] == EXPERIMENT_NUM_RETRIES
        assert contract["optimizer"]["max_metric_calls"] == 100
        assert contract["optimizer"]["seed_style"] == "structured"
        assert set(contract["optimizer"]["component_kinds"].values()) == {"system_prompt"}
        assert contract["optimizer"]["semantic_action_space"] == SEMANTIC_ACTION_CATALOGS["prompt"]
        assert contract["optimizer"]["semantic_controller_policy"] == CONTROLLER_POLICY_CONTRACT

    assert hotpot["schema_version"] == 6
    assert hotpot["retrieval"]["backend"] == "wiki17-bm25s"
    assert hotpot["retrieval"]["k1"] == 0.9
    assert hotpot["retrieval"]["b"] == 0.4
    assert hotpot["optimizer"]["reflection_minibatch_size"] == 3
    assert hotpot["optimizer"]["frontier_type"] == "instance"
    assert hotpot["optimizer"]["skip_perfect_score"] is True
    assert hotpot["program"]["parallel_workers"] == 32
    assert hotpot["program"]["predictor_type"] == "dspy_chain_of_thought"
    assert hotpot["program"]["predictor_adapter"] == "dspy_chat_adapter"
    assert hotpot["program"]["dspy_runtime_version"] == "2.6.23"
    assert hotpot["program"]["dspy_runtime_commit"] == "62dc3b634d7dc0c4889abcf905cb4c391ea6b396"
    assert hotpot["program"]["component_output_fields"] == {
        "summarize1": ["reasoning", "summary"],
        "create_query_hop2": ["reasoning", "query"],
        "summarize2": ["reasoning", "summary"],
        "final_answer": ["reasoning", "answer"],
    }
    assert hover["schema_version"] == 5
    assert hover["benchmark"] == "hover-train-wiki17"
    assert hover["retrieval"]["backend"] == "wiki17-bm25s"
    assert hover["retrieval"]["k1"] == 0.9
    assert hover["retrieval"]["b"] == 0.4
    assert hover["optimizer"]["reflection_minibatch_size"] == 3
    assert hover["optimizer"]["frontier_type"] == "instance"
    assert hover["optimizer"]["skip_perfect_score"] is True
    assert hover["program"]["parallel_workers"] == 32
    assert hover["program"]["retrieval_k"] == 7
    assert hover["program"]["final_retrieval_k"] == 10
    assert hover["program"]["predictor_type"] == "dspy_chain_of_thought"
    assert hover["program"]["predictor_adapter"] == "dspy_chat_adapter"
    assert hover["program"]["component_output_fields"] == {
        "summarize1": ["reasoning", "summary"],
        "create_query_hop2": ["reasoning", "query"],
        "summarize2": ["reasoning", "summary"],
        "create_query_hop3": ["reasoning", "query"],
    }
    assert hover["models"]["solver_decoding"] == {
        "temperature": 1.0,
        "top_p": 0.95,
        "top_k": 20,
        "max_tokens": 16_384,
    }

    assert hover_run_key("react_v2", hover_args) != hover_run_key("react_v2", _hotpot_args(final_retrieval_k=11))


def test_deepseek_contract_uses_the_deepseek_pair_and_decoding() -> None:
    """Record the separate DeepSeek condition without Qwen settings."""
    args = _hotpot_args(
        solver_model=DEEPSEEK_V4_FLASH_MODEL,
        reflection_model=DEEPSEEK_V4_FLASH_MODEL,
        solver_api_base=None,
        reflection_api_base=None,
    )

    contract = build_hotpotqa_run_contract("react_v2", args)

    assert contract["models"] == {
        "api_profile": "direct",
        "solver": DEEPSEEK_V4_FLASH_MODEL,
        "solver_runtime": DEEPSEEK_V4_FLASH_MODEL,
        "solver_api_base": None,
        "solver_decoding": {
            "temperature": 1.0,
            "top_p": 0.95,
            "max_tokens": 16_384,
            "reasoning_effort": "max",
        },
        "solver_request_overrides": {},
        "solver_num_retries": 0,
        "reflection": DEEPSEEK_V4_FLASH_MODEL,
        "reflection_runtime": DEEPSEEK_V4_FLASH_MODEL,
        "reflection_api_base": None,
        "reflection_decoding": {
            "temperature": 1.0,
            "top_p": 0.95,
            "max_tokens": 16_384,
            "reasoning_effort": "max",
        },
        "reflection_request_overrides": {},
        "reflection_num_retries": 0,
    }


@pytest.mark.parametrize(
    ("canonical_model", "runtime_model"),
    [
        (QWEN3_8_27B_MODEL, QWEN3_8_27B_OPENROUTER_MODEL),
        (DEEPSEEK_V4_FLASH_MODEL, DEEPSEEK_V4_FLASH_0731_OPENROUTER_MODEL),
    ],
)
def test_openrouter_profile_separates_experiment_identity_from_runtime(
    canonical_model: str,
    runtime_model: str,
) -> None:
    """Record canonical roles while routing all three ReAct roles identically.

    Args:
        canonical_model: Scientific model identity assigned to both roles.
        runtime_model: Exact OpenRouter model slug used for completions.
    """
    args = _hotpot_args(
        api_profile="openrouter",
        solver_model=canonical_model,
        reflection_model=canonical_model,
        solver_api_base=None,
        reflection_api_base=None,
    )
    reflection_kwargs = {
        "num_retries": EXPERIMENT_NUM_RETRIES,
        **experiment_decoding(runtime_model),
        **experiment_request_overrides(runtime_model),
    }

    contract = build_hotpotqa_run_contract("react_v2", args)
    config, _ = build_hotpotqa_config("react_v2", args, reflection_kwargs)
    strategy = config.reflection.reflection_strategy

    assert resolve_experiment_model(canonical_model, "openrouter") == runtime_model
    assert contract["models"]["api_profile"] == "openrouter"
    assert contract["models"]["solver"] == canonical_model
    assert contract["models"]["solver_runtime"] == runtime_model
    assert contract["models"]["solver_request_overrides"] == experiment_request_overrides(runtime_model)
    assert contract["models"]["reflection"] == canonical_model
    assert contract["models"]["reflection_runtime"] == runtime_model
    assert config.reflection.reflection_lm == runtime_model
    assert strategy is not None
    assert strategy.proposer_model == canonical_model
    assert strategy.base_lm.model == runtime_model
    assert strategy.base_lm.completion_kwargs["extra_body"] == experiment_request_overrides(runtime_model)["extra_body"]
    assert strategy.manifestor_lm.model == runtime_model
    assert (
        strategy.manifestor_lm.completion_kwargs["extra_body"]
        == experiment_request_overrides(runtime_model)["extra_body"]
    )


def test_openrouter_profile_changes_the_resumable_run_key() -> None:
    """Prevent direct and OpenRouter runs from sharing optimizer state."""
    direct = hotpotqa_run_key("react_v2", _hotpot_args(api_profile="direct"))
    openrouter = hotpotqa_run_key("react_v2", _hotpot_args(api_profile="openrouter"))

    assert direct != openrouter


def test_openrouter_pin_reaches_react_native_tool_calls(monkeypatch) -> None:
    """Forward the same endpoint policy through ReAct's tool-call path.

    Args:
        monkeypatch: Pytest fixture used to replace LiteLLM completion.
    """
    runtime_model = QWEN3_8_27B_OPENROUTER_MODEL
    request_overrides = experiment_request_overrides(runtime_model)
    strategy, _ = build_react_v2_strategy(
        reflection_model=runtime_model,
        task_model=QWEN3_8_27B_MODEL,
        proposer_model=QWEN3_8_27B_MODEL,
        lm_kwargs={**experiment_decoding(runtime_model), **request_overrides},
        level=2,
        edit_tool_set="broad",
        template_family="auto",
        component_kinds={"summarize1": "system_prompt"},
    )
    calls = []

    def completion(**kwargs):
        """Capture a native-tool request and return an empty terminal turn.

        Args:
            **kwargs: LiteLLM completion arguments under test.

        Returns:
            Minimal response containing no tool calls.
        """
        calls.append(kwargs)
        message = SimpleNamespace(content="", tool_calls=[])
        return SimpleNamespace(choices=[SimpleNamespace(message=message, finish_reason="stop")])

    monkeypatch.setattr(litellm, "completion", completion)

    strategy.base_lm.complete_with_tools(
        [{"role": "user", "content": "Edit the section."}],
        [{"type": "function", "function": {"name": "REPLACE_TEXT", "parameters": {"type": "object"}}}],
    )

    assert calls[0]["model"] == runtime_model
    assert calls[0]["extra_body"] == request_overrides["extra_body"]
    assert calls[0]["tool_choice"] == "auto"


def test_experiment_model_pair_rejects_cross_model_runs() -> None:
    """Reject a Qwen student paired with the DeepSeek proposer."""
    with pytest.raises(ValueError, match="same model"):
        validate_experiment_model_pair(QWEN3_8_27B_MODEL, DEEPSEEK_V4_FLASH_MODEL)


def test_experiment_model_pair_rejects_unknown_models() -> None:
    """Reject homogeneous pairs outside the two configured experiment arms."""
    with pytest.raises(ValueError, match="Unsupported experiment model"):
        validate_experiment_model_pair("provider/unknown", "provider/unknown")


def test_hover_vanilla_and_react_v2_isolate_only_the_proposal_strategy() -> None:
    """Keep every non-treatment HoVer contract axis identical across the pair."""
    args = _hotpot_args(final_retrieval_k=10)
    vanilla = deepcopy(build_hover_run_contract("vanilla", args))
    react = deepcopy(build_hover_run_contract("react_v2", args))

    assert vanilla["models"] == react["models"]
    assert vanilla["program"] == react["program"]
    assert vanilla["retrieval"] == react["retrieval"]
    assert vanilla["data"] == react["data"]

    vanilla.pop("condition")
    react.pop("condition")
    treatment_fields = {
        "reflection_level",
        "edit_tool_set",
        "semantic_action_space",
        "semantic_controller_policy",
        "vanilla_reflection_prompt",
    }
    for field in treatment_fields:
        vanilla["optimizer"].pop(field)
        react["optimizer"].pop(field)

    assert vanilla == react


def test_hover_react_v2_uses_an_experiment_seeded_controller_rng() -> None:
    """Isolate Controller sampling from process-global random state."""
    args = _hotpot_args(final_retrieval_k=10, seed=19)
    reflection_kwargs = {"num_retries": EXPERIMENT_NUM_RETRIES, **experiment_decoding(args.reflection_model)}
    config, selector = build_hover_config("react_v2", args, reflection_kwargs)
    vanilla_config, vanilla_selector = build_hover_config("vanilla", args, reflection_kwargs)

    assert selector is None
    assert vanilla_selector is None
    assert config.engine.seed == 19
    assert config.engine.max_workers == 32
    assert config.engine.val_evaluation_policy == "full_eval"
    assert config.engine.candidate_selection_strategy == "pareto"
    assert config.engine.frontier_type == "instance"
    assert config.engine.acceptance_criterion == "strict_improvement"
    assert config.reflection.reflection_lm_kwargs == {
        "num_retries": EXPERIMENT_NUM_RETRIES,
        **experiment_decoding(QWEN3_8_27B_MODEL),
    }
    assert config.reflection.skip_perfect_score is True
    assert config.reflection.perfect_score == 1.0
    assert config.reflection.batch_sampler == "epoch_shuffled"
    assert config.reflection.reflection_minibatch_size == 3
    assert config.reflection.module_selector == "round_robin"
    assert config.reflection.reflection_prompt_template == InstructionProposalSignature.default_prompt_template
    assert config.reflection.reflection_strategy is not None
    assert config.reflection.reflection_strategy.rng.getstate() == random.Random(19).getstate()
    assert vanilla_config.engine.seed == config.engine.seed
    assert vanilla_config.engine.max_workers == config.engine.max_workers
    assert vanilla_config.engine.val_evaluation_policy == config.engine.val_evaluation_policy
    assert vanilla_config.engine.candidate_selection_strategy == config.engine.candidate_selection_strategy
    assert vanilla_config.engine.frontier_type == config.engine.frontier_type
    assert vanilla_config.engine.acceptance_criterion == config.engine.acceptance_criterion
    assert vanilla_config.reflection.skip_perfect_score == config.reflection.skip_perfect_score
    assert vanilla_config.reflection.perfect_score == config.reflection.perfect_score
    assert vanilla_config.reflection.batch_sampler == config.reflection.batch_sampler
    assert vanilla_config.reflection.reflection_minibatch_size == config.reflection.reflection_minibatch_size
    assert vanilla_config.reflection.module_selector == config.reflection.module_selector
    assert vanilla_config.reflection.reflection_prompt_template == config.reflection.reflection_prompt_template


def test_run_contract_rejects_drift_and_legacy_state(tmp_path: Path) -> None:
    """Accept exact resume state while rejecting drift and unversioned legacy state.

    Args:
        tmp_path: Pytest directory used for isolated run contracts.
    """
    contract = build_hotpotqa_run_contract("react_v2", _hotpot_args())
    run_dir = tmp_path / "run"

    path = ensure_wikipedia_run_contract(run_dir, contract)

    assert ensure_wikipedia_run_contract(run_dir, contract) == path
    with pytest.raises(ValueError, match="different Wikipedia benchmark configuration"):
        ensure_wikipedia_run_contract(run_dir, {**contract, "tag": "drift"})

    legacy_dir = tmp_path / "legacy"
    legacy_dir.mkdir()
    (legacy_dir / "gepa_state.bin").write_bytes(b"legacy")
    with pytest.raises(ValueError, match="GEPA state but no wikipedia-run-contract.json"):
        ensure_wikipedia_run_contract(legacy_dir, contract)


@pytest.mark.parametrize("dump_candidates", [dump_hotpotqa_candidates, dump_hover_candidates])
def test_candidate_artifacts_embed_run_contract(tmp_path: Path, dump_candidates) -> None:
    """Embed the exact run contract in both benchmark candidate artifacts.

    Args:
        tmp_path: Pytest directory receiving the artifact.
        dump_candidates: Parameterized benchmark artifact writer.
    """
    contract = build_hotpotqa_run_contract("react_v2", _hotpot_args())
    result = SimpleNamespace(
        best_idx=0,
        total_metric_calls=100,
        num_full_val_evals=1,
        candidates=[{"prompt": "candidate"}],
        parents=[None],
        val_aggregate_scores=[1.0],
        discovery_eval_counts=[1],
    )

    path = dump_candidates(result, str(tmp_path / dump_candidates.__module__.replace(".", "-")), contract)

    assert json.loads(Path(path).read_text())["run_contract"] == contract


@pytest.mark.parametrize("condition", ["random", "action"])
def test_stateless_conditions_use_the_canonical_provider_action_menu(condition: str) -> None:
    """Share one provider-aware semantic menu across stateless conditions.

    Args:
        condition: Random or verbalized stateless selector condition.
    """
    args = _hotpot_args()
    template = TEMPLATE_FAMILIES["alibaba"]["system_prompt"]
    contract = build_hotpotqa_run_contract(condition, args)
    config, selector = build_hotpotqa_config(condition, args, {})
    hover_config, hover_selector = build_hover_config(condition, _hotpot_args(final_retrieval_k=10), {})
    expected_menu = [
        StatelessActionConstraint(spec, section, template) for section in template.sections for spec in SEMANTIC_ACTIONS
    ]
    expected_contract = {
        "version": STATELESS_ACTION_MENU_VERSION,
        "semantic_action_catalog_version": SEMANTIC_ACTION_CATALOGS[template.kind]["version"],
        "kind": template.kind,
        "sections": list(template.sections),
        "choices": [
            {
                "id": choice.menu_id,
                "semantic_action": choice.semantic_action.name,
                "operator": choice.edit_tool.value,
                "target_section": choice.target_section,
            }
            for choice in expected_menu
        ],
    }

    assert contract["optimizer"]["semantic_action_space"] == SEMANTIC_ACTION_CATALOGS["prompt"]
    assert contract["optimizer"]["semantic_controller_policy"] is None
    assert contract["optimizer"]["stateless_action_menu"] == expected_contract
    assert contract["optimizer"]["stateless_selector_policy"] == stateless_selector_policy_contract(
        "random" if condition == "random" else "verbalized"
    )
    assert config.reflection.action_selector is selector
    assert hover_config.reflection.action_selector is hover_selector
    assert [choice.menu_id for choice in hover_selector.actions] == [choice.menu_id for choice in expected_menu]
    assert [choice.menu_id for choice in selector.actions] == [choice.menu_id for choice in expected_menu]
    assert {choice.target_section for choice in selector.actions} == set(template.sections)
    assert all(choice.edit_tool is choice.semantic_action.edit_tool for choice in selector.actions)


def test_stateless_action_menu_contract_matches_between_wikipedia_benchmarks() -> None:
    """Persist identical stateless action-menu contracts for HotPotQA and HOVER."""
    args = _hotpot_args(final_retrieval_k=10)
    expected = build_hotpotqa_run_contract("random", args)["optimizer"]["stateless_action_menu"]

    for build_contract, schema_version in (
        (build_hotpotqa_run_contract, 6),
        (build_hover_run_contract, 5),
    ):
        contract = build_contract("random", args)
        assert contract["schema_version"] == schema_version
        assert contract["optimizer"]["stateless_action_menu"] == expected
        assert contract["optimizer"]["stateless_selector_policy"] == stateless_selector_policy_contract("random")
        assert "legacy_actions" not in contract["optimizer"]
