"""Render the shell launchers' shared constants from their Python owners.

Regenerate with ``uv run python -m examples.common.launcher_constants``; redirect
stdout to ``scripts/della/runtime_constants.sh``. The parity test rejects stale
generated output before a source revision can be qualified.
"""

import shlex

from examples.common.experiment_models import (
    DEEPSEEK_V4_1_FLASH_MODEL,
    DEEPSEEK_V4_1_FLASH_REPO,
    EXPERIMENT_CONTEXT_TOKENS,
)

LAUNCHER_DEFAULTS = {
    "FOREST_CONTEXT_TOKENS": EXPERIMENT_CONTEXT_TOKENS,
    "FOREST_GPU_MEMORY_UTILIZATION": 0.92,
    "FOREST_MAX_BATCHED_TOKENS": 16_384,
    "FOREST_ENGINE_READY_TIMEOUT_SECONDS": 3600,
    "FOREST_DEEPSEEK_REPO": DEEPSEEK_V4_1_FLASH_REPO,
    "FOREST_DEEPSEEK_MODEL": DEEPSEEK_V4_1_FLASH_MODEL,
}


def render_shell_constants() -> str:
    """Return safely quoted Bash assignments without requiring Python at startup."""
    header = "# Generated by examples.common.launcher_constants; edit the Python source.\n"
    return header + "".join(f"{name}={shlex.quote(str(value))}\n" for name, value in LAUNCHER_DEFAULTS.items())


if __name__ == "__main__":
    print(render_shell_constants(), end="")
