"""Render the shell launchers' shared constants from their Python owners.

Regenerate with ``uv run python -m examples.common.launcher_constants``; redirect
stdout to ``scripts/della/runtime_constants.sh``. The parity test rejects stale
generated output before a source revision can be qualified.
"""

import shlex

from examples.common.experiment_models import (
    DEEPSEEK_V4_1_FLASH_MODEL,
    DEEPSEEK_V4_1_FLASH_PROFILE,
    DEEPSEEK_V4_1_FLASH_REPO,
    DEEPSEEK_V4_1_FLASH_REVISION,
    EXPERIMENT_CONTEXT_TOKENS,
    QWEN3_8_27B_MODEL,
    QWEN3_8_27B_PROFILE,
    QWEN3_8_27B_REPO,
    QWEN3_8_27B_REVISION,
)
from examples.hotpotqa.benchmark_settings import EXPANDED_METRIC_CALLS, STANDARD_METRIC_CALLS
from gepa.strategies.forest_constants import REACT_EDITOR_MODE, SINGLE_CALL_EDITOR_MODE

LAUNCHER_DEFAULTS = {
    "FOREST_CONTEXT_TOKENS": EXPERIMENT_CONTEXT_TOKENS,
    "FOREST_GPU_MEMORY_UTILIZATION": 0.92,
    "FOREST_MAX_BATCHED_TOKENS": 16_384,
    "FOREST_HEALTH_TIMEOUT_SECONDS": 1800,
    "FOREST_ENGINE_READY_TIMEOUT_SECONDS": 3600,
    "FOREST_QWEN_PROFILE": QWEN3_8_27B_PROFILE,
    "FOREST_DEEPSEEK_PROFILE": DEEPSEEK_V4_1_FLASH_PROFILE,
    "FOREST_QWEN_REPO": QWEN3_8_27B_REPO,
    "FOREST_DEEPSEEK_REPO": DEEPSEEK_V4_1_FLASH_REPO,
    "FOREST_QWEN_MODEL": QWEN3_8_27B_MODEL,
    "FOREST_DEEPSEEK_MODEL": DEEPSEEK_V4_1_FLASH_MODEL,
    "FOREST_QWEN_REVISION": QWEN3_8_27B_REVISION,
    "FOREST_DEEPSEEK_REVISION": DEEPSEEK_V4_1_FLASH_REVISION,
    "FOREST_REACT_EDITOR_MODE": REACT_EDITOR_MODE,
    "FOREST_SINGLE_CALL_EDITOR_MODE": SINGLE_CALL_EDITOR_MODE,
    "HOTPOTQA_STANDARD_METRIC_CALLS": STANDARD_METRIC_CALLS,
    "HOTPOTQA_EXPANDED_METRIC_CALLS": EXPANDED_METRIC_CALLS,
}


def render_shell_constants() -> str:
    """Return safely quoted Bash assignments without requiring Python at startup."""
    header = "# Generated by examples.common.launcher_constants; edit the Python source.\n"
    return header + "".join(f"{name}={shlex.quote(str(value))}\n" for name, value in LAUNCHER_DEFAULTS.items())


if __name__ == "__main__":
    print(render_shell_constants(), end="")
