"""Preserve HotPotQA's public names for the shared benchmark role budgets."""

from examples.common.model_settings import (
    OPTIMIZER_MAX_TOKENS as HOTPOTQA_OPTIMIZER_MAX_TOKENS,
    OPTIMIZER_THINKING_TOKENS as HOTPOTQA_OPTIMIZER_THINKING_TOKENS,
    REQUEST_TIMEOUT_SECONDS as HOTPOTQA_REQUEST_TIMEOUT_SECONDS,
    SCIENTIFIC_REQUEST_SEED as HOTPOTQA_SCIENTIFIC_REQUEST_SEED,
    SOLVER_MAX_TOKENS as HOTPOTQA_SOLVER_MAX_TOKENS,
    SOLVER_THINKING_TOKENS as HOTPOTQA_SOLVER_THINKING_TOKENS,
)

__all__ = [
    "HOTPOTQA_OPTIMIZER_MAX_TOKENS",
    "HOTPOTQA_OPTIMIZER_THINKING_TOKENS",
    "HOTPOTQA_REQUEST_TIMEOUT_SECONDS",
    "HOTPOTQA_SCIENTIFIC_REQUEST_SEED",
    "HOTPOTQA_SOLVER_MAX_TOKENS",
    "HOTPOTQA_SOLVER_THINKING_TOKENS",
]
