authors:
  lakshya:
    name: Lakshya A Agrawal
    description: PhD Student, UC Berkeley Sky Lab
    avatar: https://github.com/LakshyAAAgrawal.png
    url: https://x.com/LakshyAAAgrawal
  shangyin:
    name: Shangyin Tan
    description: PhD Student, UC Berkeley Sky Lab
    avatar: https://github.com/Shangyint.png
    url: https://shangyit.me
  rohit:
    name: Rohit Sandadi
    description: Undergraduate Researcher, UC Berkeley Sky Lab
    avatar: https://github.com/rohitsandadi.png
    url: https://rohitsandadi.github.io
  alex:
    name: Alexandros G. Dimakis
    description: Professor, UC Berkeley EECS
    avatar: https://github.com/Alex-adim.png
    url: https://people.eecs.berkeley.edu/~alexdimakis/
  donghyun:
    name: Donghyun Lee
    description: PhD Student, UC Berkeley
    avatar: https://pbs.twimg.com/profile_images/1908160333199380480/2fX9J_BK_400x400.jpg
    url: https://x.com/lukedhlee
  wenjie:
    name: Wenjie Ma
    description: PhD Student, UC Berkeley
    avatar: https://github.com/euclidgame.png
    url: https://wenjiema.com
  karim:
    name: Karim Elmaaroufi
    description: PhD Student, UC Berkeley Sky Lab
    avatar: https://github.com/KE7.png
    url: https://kael.tech.blog/
  joey:
    name: Joseph E. Gonzalez
    description: Associate Professor, UC Berkeley EECS
    avatar: https://github.com/jegonzal.png
    url: https://people.eecs.berkeley.edu/~jegonzal/
  ion:
    name: Ion Stoica
    description: Professor, UC Berkeley EECS
    avatar: https://people.eecs.berkeley.edu/~istoica/ion_picture_small.jpg
    url: https://people.eecs.berkeley.edu/~istoica/
  omar:
    name: Omar Khattab
    description: Assistant Professor, MIT EECS
    avatar: https://github.com/okhat.png
    url: https://omarkhattab.com/
  matei:
    name: Matei Zaharia
    description: Professor, UC Berkeley EECS
    avatar: https://github.com/mateiz.png
    url: https://people.eecs.berkeley.edu/~matei/
  sewon:
    name: Sewon Min
    description: Assistant Professor, UC Berkeley
    avatar: https://www.sewonmin.com/assets/sewon-2024.jpg
    url: https://www.sewonmin.com/
  koushik:
    name: Koushik Sen
    description: Professor, UC Berkeley
    avatar: https://people.eecs.berkeley.edu/~ksen/ksen.jpeg
    url: https://people.eecs.berkeley.edu/~ksen/?rnd=1771147393589
  dan:
    name: Dan Klein
    description: Professor, UC Berkeley
    avatar: https://bakarfellows.berkeley.edu/profile/dan-klein/
    url: https://www2.eecs.berkeley.edu/Faculty/Homepages/klein.html
  rodolfo:
    name: Rodolfo Nobrega
    description: Machine Learning Engineer
    avatar: https://github.com/rodolfonobrega.png
    url: https://github.com/rodolfonobrega
  sanjit:
    name: Sanjit A. Seshia
    description: Professor, UC Berkeley
    avatar: https://people.eecs.berkeley.edu/~sseshia/SanjitSeshia_webphoto.jpg
    url: https://people.eecs.berkeley.edu/~sseshia/
  hanchen:
    name: Hanchen Li
    description: PhD Student, UC Berkeley
    avatar: https://github.com/Hanchenli.png
    url: https://x.com/lihanc02
  runyuan:
    name: Runyuan He
    description: Visiting Student, UC Berkeley
    avatar: https://github.com/RunyuanHe.png
    url: https://runyuanhe.github.io/
  qizheng:
    name: Qizheng Zhang
    description: PhD Student, Stanford University
    avatar: https://github.com/qizheng-zhang.png
    url: https://qizheng-zhang.github.io
  changxiu:
    name: Changxiu Ji
    description: Undergraduate Student, Stanford University
    avatar: https://github.com/changxiuji.png
    url: https://github.com/changxiuji
  qiuyang:
    name: Qiuyang Mang
    description: PhD Student, UC Berkeley
    avatar: https://github.com/qiuyangmang.png
    url: https://github.com/qiuyangmang
  xiaokun:
    name: Xiaokun Chen
    description: Tensormesh
    avatar: https://github.com/xiaokunchen.png
    url: https://github.com/xiaokunchen
  weiliang:
    name: Wei-Liang Liao
    description: Master Student, UC Berkeley
    avatar: https://github.com/WeiLiangLiao.png
    url: https://github.com/WeiLiangLiao
  eric:
    name: Eric Yang
    description: Gradient Network
    avatar: https://github.com/ericyang.png
    url: https://github.com/ericyang
  alvin:
    name: Alvin Cheung
    description: Professor, UC Berkeley EECS
    avatar: https://github.com/AlvinCheung.png
    url: https://people.eecs.berkeley.edu/~akcheung/
  james:
    name: James Zou
    description: Professor, Stanford University
    avatar: https://github.com/jamesyzou.png
    url: https://www.james-zou.com/
  kunle:
    name: Kunle Olukotun
    description: Professor, Stanford University
    avatar: https://github.com/kunle.png
    url: https://profiles.stanford.edu/kunle-olukotun
  rishabh_tiwari:
    name: Rishabh Tiwari
    description: Researcher
    avatar: https://github.com/rishabh-16.png
    url: https://rishabhtiwari.ai/
  kusha:
    name: Kusha Sareen
    description: Researcher
    avatar: https://github.com/kushasareen.png
    url: https://kushasareen.github.io/
  kurt:
    name: Kurt Keutzer
    description: Professor, UC Berkeley EECS
    avatar: https://github.com/keutzer.png
    url: https://people.eecs.berkeley.edu/~keutzer/
  inderjit:
    name: Inderjit S Dhillon
    description: Professor, UT Austin
    avatar: https://github.com/inderjit-dhillon.png
    url: https://www.cs.utexas.edu/people/faculty-researchers/inderjit-dhillon
  rishabh_agarwal:
    name: Rishabh Agarwal
    description: Research Scientist
    avatar: https://github.com/agarwl.png
    url: https://agarwl.github.io/
  devvrit:
    name: Devvrit Khatri
    description: PhD Student
    avatar: https://github.com/devvrit.png
    url: https://github.com/devvrit
  lutfi:
    name: Lutfi Eren Erdogan
    description: Master Student, UC Berkeley
    avatar: https://github.com/xTRam1.png
    url: https://scholar.google.com/citations?user=BiprbFAAAAAJ&hl=en
  gepa-team:
    name: GEPA Team
    description: GEPA Team
    avatar: https://github.com/gepa-ai.png
    url: https://gepa-ai.github.io
  ben:
    name: Jialin Zhang
    description: Undergraduate Researcher, UC Berkeley
    avatar: https://github.com/benzhang04.png
    url: https://x.com/benzhang04
